/* MyLibHeader.h generated by valac 0.40.17, the Vala compiler, do not modify */


#ifndef __MYLIBHEADER_H__
#define __MYLIBHEADER_H__

#ifdef __cplusplus
extern "C" {
#endif


char* vala_main(void);


#ifdef __cplusplus
}
#endif

#endif
